language: python

notifications:
  email: false

python:
  - 3.7

before_install:
  - pip3 install pytest
  - pip3 install codecov

install:
  - pip install -r requirements.txt
  - pip install .
  - wget -P model https://github.com/nanguoyu/Intelligent-Interactive-Systems-Project/releases/download/latest/End2endWeights-best.hdf5
  - wget -P model https://github.com/nanguoyu/Intelligent-Interactive-Systems-Project/releases/download/0.1/Sub1-weights-best.hdf5
  - wget -P model https://github.com/nanguoyu/Intelligent-Interactive-Systems-Project/releases/download/0.1/Sub2-weights.hdf5
script:
  - chmod +x ./start_app_macos.sh
  - ./start_app_macos.sh
  - pytest
  - coverage run -p ./tests/test_sub1_model.py
  - coverage run -p ./tests/test_end2end_model.py
  - coverage combine

after_success:
  - codecov